name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  labels:
    description: 'Labels'
    required: true
    default: ''
outputs:
  newlabels:
    description: 'New labels'
runs:
  using: 'node20'
  main: 'index.js'